server:
  port: 8501

spring:
  application:
    name: account-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spcloud:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcloud

    username: cassandra
    password: cassandra